site_name: Test Documentation
site_dir: site
docs_dir: docs
site_description: Test Documentation

dev_addr: 'localhost:8111'
repo_url: https://github.com/Natkeeran/mkdocs_test/

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'assets/claw.png'
  social:
    - type: 'twitter'


theme: material


pages:
- Welcome: 'index.md'
- User Documentation:
    - 'Introduction to Doc': 'folder1/page1.md'
- Section 2:
    - 'Section 2.1': 'folder2/page2.md'
    - 'Section 2.2': 'folder2/page3.md'
- Section 3:
    - 'How to contribute': 'folder3/page4.md'







